server:
  port: 8042

spring:
  application:
    name: product
#  config:
#    import: optional:configserver:http://localhost:8888    
    
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/ShopSphereProduct
    username: root
    password: cogentUniversity
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
