server:
  port: 8040

spring:
  application:
    name: gateway
#  main:
#    allow-circular-references: true
#---------------------------------------------------------------------------------------------------------
#added for the -> FRONTEND
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#---------------------------------------------------------------------------------------------------------
      routes:
        - id: user
          uri: http://localhost:8041
          predicates:
            - Path=/auth/**, /admin/**
          filters:
            - AuthFilter
      
        - id: product
          uri: http://localhost:8042
          predicates:
            - Path=/product/**
          filters:
            - AuthFilter

        - id: cart
          uri: http://localhost:8043
          predicates:
            - Path=/cart/**
          filters:
            - AuthFilter
            
        - id: wishlist
          uri: http://localhost:8044
          predicates:
            - Path=/wishlist/**
          filters:
            - AuthFilter 
            
        - id: order
          uri: http://localhost:8045
          predicates:
            - Path=/order/**
          filters:
            - AuthFilter 
            
        - id: discount
          uri: http://localhost:8046
          predicates:
            - Path=/discount/**
          filters:
            - AuthFilter 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#-------------
logging:
  level:
    root: warn
#------------- 
